# Generated by Django 5.1.6 on 2025-04-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_restaurant_order_driver_lat_order_driver_lng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='restaurant_name',
            new_name='restaurant',
        ),
    ]
