# Generated by Django 5.1.6 on 2025-04-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_restaurant_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='route_coords_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform',
            field=models.CharField(choices=[('DoorDash', 'DoorDash'), ('UberEats', 'UberEats'), ('GrubHub', 'GrubHub')], max_length=20),
        ),
    ]
