# Generated by Django 5.1.6 on 2025-04-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_route_coords_json_alter_order_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='route_coords_json',
            new_name='route',
        ),
    ]
