# Generated by Django 5.1.6 on 2025-04-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_route_coords_json_order_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location_lng',
            field=models.FloatField(default=-87.938),
        ),
    ]
